{"level":"error","message":"Translation error for word 'breakthrough': Error: ðŸ’¥ Test error for logger\n    at GET (src\\app\\api\\translate\\route.ts:14:11)\n  12 |\n  13 |   try {\n> 14 |     throw new Error(\"ðŸ’¥ Test error for logger\");\n     |           ^\n  15 |     const translated = await translate(word, {from, to });\n  16 |\n  17 |     return NextResponse.json({ translation: translated }); {\n  [stack]: [Getter/Setter],\n  [message]: 'ðŸ’¥ Test error for logger',\n  [__NEXT_ERROR_CODE]: 'E394',\n  [Symbol(nodejs.util.inspect.custom)]: undefined\n}","service":"next-app","timestamp":"2025-10-31 12:01:05"}
{"level":"error","message":"Translation error for word 'trade': Error: ðŸ’¥ Test error for logger\n    at GET (src\\app\\api\\translate\\route.ts:14:11)\n  12 |\n  13 |   try {\n> 14 |     throw new Error(\"ðŸ’¥ Test error for logger\");\n     |           ^\n  15 |     const translated = await translate(word, {from, to });\n  16 |\n  17 |     return NextResponse.json({ translation: translated }); {\n  [stack]: [Getter/Setter],\n  [message]: 'ðŸ’¥ Test error for logger',\n  [__NEXT_ERROR_CODE]: 'E394',\n  [Symbol(nodejs.util.inspect.custom)]: undefined\n}","service":"next-app","timestamp":"2025-10-31 12:01:10"}
